- src/maxminddb.c
I didn't create an issue on your side, but I can if needed (I'm still new at this and don't know proper procedures).
We had an issue on one of our live boxes where we got back MMDB_IO_ERROR on our call to MMDB_open.  Looking at the code, I noticed in map_file() that this can only be returned from a failure on MapViewOfFile (for the Windows variant).  I also noticed that CreateFileMappingA on the line above that didn't actually have its result checked.
This update checks the result of CreateFileMappingA for failure, and goes to "cleanup" on NULL.  I called CreateFileMappingA with a random number, and it did indeed return NULL and not INVALID_HANDLE_VALUE.
Anyway, this change will return immediately if the CreateFileMappingA fails, so we don't do the next line (MapViewOfFile) in that error …
> Enhancement - Check return value of CreateFileMappingA

- dev-bin/regen-prototypes.pl
- src/maxminddb.c
The Windows version of map_file shared almost no code with the
non-Windows version. Separating out the two versions of the function
completely make both of them much easier to read.
> Remove unused assignment. Reorganize.

- Changes.md
- src/maxminddb.c
These were found using afl-fuzz. There are several more similar failure
that warrant investigation. If we want to add tests, I have several
corrupt databases we could add, but these are trivially reproducible
when using the existing test databases as input to afl-fuzz.
> Fix several segfaults from missing bounds checks

- Changes.md
- README.md
- src/maxminddb.c
* Pointers to pointers are no longer allowed, per the spec.
* More error checking is done, particularly when reading the metadata.
* Data structures are now limited to a depth of 512 when using `MMDB_get_entry_data_list`.
> Fix several hangs and crashes

- Changes.md
- src/maxminddb.c
- t/ipv6_lookup_in_ipv4_t.c
The only plausible reason for using `getaddrinfo` over `inet_pton` is that it can detect address family. This change uses that functionality and removes some unnecessary flags. It also fixes an error so that it works with the sockaddr function.
OTOH, we could switch to `inet_pton`, but it is complicated by the fact that we made the `getaddrinfo` error part of our public interface.
> Simplify IP resolution

- Changes.md
- configure.ac
- src/maxminddb.c
Hopefully this will fix https://github.com/maxmind/libmaxminddb/issues/120
(breakage on Sparc systems).
> Use autoconf to check system endianness rather than compiler macros

- .travis.yml
- t/data_entry_list_t.c
- t/data_types_t.c
- t/dump_t.c
- t/maxminddb_test_helper.c
- t/metadata_t.c
- t/read_node_t.c
- t/version_t.c
This required quite a few code changes as libtap apparently does not put
parens around parameter names.
> Upgrade libtap to latest version

- .gitmodules
recursive cloning fails in environments where the git protocol is blocked (firewalled)
> use https submodule urls

- Changes.md
- appveyor.yml
- dev-bin/regen-prototypes.pl
- projects/VS12-tests/bad_pointers.vcxproj
- projects/VS12-tests/basic_lookup.vcxproj
- projects/VS12-tests/data_entry_list.vcxproj
- projects/VS12-tests/dump.vcxproj
- projects/VS12-tests/get_value.vcxproj
- projects/VS12-tests/get_value_pointer_bug.vcxproj
- projects/VS12-tests/ipv4_start_cache.vcxproj
- projects/VS12-tests/ipv6_lookup_in_ipv4.vcxproj
- projects/VS12-tests/metadata.vcxproj
- projects/VS12-tests/metadata_pointers.vcxproj
- projects/VS12-tests/no_map_get_value.vcxproj
- projects/VS12-tests/read_node.vcxproj
- projects/VS12-tests/version.vcxproj
- projects/VS12/libmaxminddb.sln
- src/maxminddb.c
- t/Makefile.am
- t/bad_databases_t.c
- t/get_value_t.c
- t/maxminddb_test_helper.h
A corrupt database could cause a segmentation fault if it had a data
pointer large enough to cause an overflow in the existing bound checks.
Fixes #140.
> Fix overflow in bound checks

- bin/mmdblookup.c
(at least on 32 bit builds on Solaris Sparc).
Verbose mmdblookup output before the fix:
Build epoch:   1497876636 (1970-01-01 00:00:00 UTC)
and after the fix:
Build epoch:   1497876636 (2017-06-19 12:50:36 UTC)
The original code converted *uint64_t to *time_t by casting
the pointer. But that doesn't convert the referenced value
and for a build where a time_t is a long of size 32bits
(eg. on Solaris Sparc) probably also depending on endianess
when dereferencing the casted pointer you get the wrong half
of the 64 bits (=0).
The fix is to cast the value and use a pointer to the casted value.
> Fix wrong epoch formatting for verbose mmdblookup

- src/data-pool.c
- t/data-pool-t.c
Before this we were actually accessing the last+1 and setting that to
NULL. The list would often be valid if our last element happened to be
in a part of memory that we zeroed. This changes to correctly set the
last element in the list.
> Set the last element in the list's next pointer to NULL

- configure.ac
The rpl_malloc() entry is created by AC_FUNC_MALLOC configure check
if it does not like the default malloc implementation. The idea is
to support malloc(0). However, that is considered dangerous in any
case from a security point of view and should be avoided inside code.
So security-aware code does not need it.
On the other hand, AC_FUNC_MALLOC is known for false positives, often
resulting in the creation of calls to rpl_malloc(), which the
user would need to provide. This happens depending on compiler and
OS/distro being used.
Note that the usefulness of that macro is even questioned on the
autoconf mailing list:
https://lists.gnu.org/archive/html/autoconf/2003-02/msg00017.html
So the solution is to simply remove that macro.
Note: we have done this in the rsyslog project more than 2 …
> remove build problems related to rpl_malloc

- Changes.md
- bin/Makefile.am
- include/maxminddb.h
- src/data-pool.c
- src/data-pool.h
- src/maxminddb.c
- t/Makefile.am
- t/data-pool-t.c
This allows the pointers to list elements to be valid even when the
pool's size grows.
> Allocate in multiple chunks rather than reallocating one single chunk

- src/Makefile.am
- t/Makefile.am
As to only export symbols starting with "MMDB_" and in lieu of a proper
version script. This helps by filtering out the new data_pool_* symbols,
which are internal-only and should not exposed to applications using
libmaxminddb.
The change to LDFLAGS would introduce a test failure, as data-pool-t
used those internal functions, but this is addressed by adding
src/data-pool.c to data-pool-t's SOURCES, as suggested by Will Storey.
This resolves #160.
> Add -export-symbols-regexp to LDFLAGS

- bin/mmdblookup.c
- configure.ac
Primarily I wanted a way to use a defined set of IPs for benchmarking. However, it's also useful for sanity checking that changes provide the same output data as before the changes (if you ask it to dump out the entry lists, then compare that output).
> Provide a way to look up IPs from file in mmdblookup

- Makefile.am
- configure.ac
mmdblookup now depends on pthread.h which can be disabled on some
toolchains so add an option to be able to compile libmaxminddb without
this binary
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> Add --disable-binaries

- bin/mmdblookup.c
- projects/VS12/maxminddb_config.h
- src/maxminddb.c
We use Windows' Unicode API internally, but we shouldn't force that choice
on consumers. Make "#define UNICODE" internal in the modules that need it.
> Don't force the Unicode API on Windows consumers.

- include/maxminddb.h
- src/maxminddb.c
- t/metadata_t.c
According to https://github.com/maxmind/libmaxminddb/issues/24, libmaxminddb is supposed to be thread safe. This pull request adds const modifiers to the MMDB_s pointer to make it clear that the structure doesn't get modified. This allows people to use a const MMDB without needing to cast away the const.
Also removes one spot that appears to be unnecessarily modifying the MMDB_s from the ip lookup method.
> Const MMDB_s

- src/maxminddb.c
```
libmaxminddb/src/maxminddb.c:344:9: error: variable 'fd' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
if (!utf16_filename) {
^~~~~~~~~~~~~~~
libmaxminddb/src/maxminddb.c:378:33: note: uninitialized use occurs here
if (INVALID_HANDLE_VALUE != fd) {
^~
libmaxminddb/src/maxminddb.c:344:5: note: remove the 'if' if its condition is always false
if (!utf16_filename) {
^~~~~~~~~~~~~~~~~~~~~~
libmaxminddb/src/maxminddb.c:348:5: note: variable 'fd' is declared here
HANDLE fd = CreateFile(utf16_filename, GENERIC_READ, FILE_SHARE_READ, NULL,
^
1 error generated.
```
> on Win32, cleanup handler in map_file can close uninitialized handle

- Changes.md
- bin/mmdblookup.c
When using verbose mode.
Closes #172.
> Display prefix length for record in mmdblookup

- include/maxminddb.h
- src/maxminddb.c
Also reduce repeated calculations.
This moderately speeds up `find_address_in_search_tree`, but given that it isn't the bottleneck, it doesn't make much difference generally.
> Simplify search tree lookup

- t/maxminddb_test_helper.h
Some file systems are case sensitive.
In file included from maxminddb_test_helper.c:11:
maxminddb_test_helper.h:16:10: fatal error: Winsock2.h: No such file or directory
16 | #include <Winsock2.h>
|          ^~~~~~~~~~~~
> Fix MinGW cross compilation

- Changes.md
- include/maxminddb.h
- src/maxminddb.c
This commit introduced an unintended ABI change. Users of this library
allocate the space for `MMDB_s`. Any increase in size of `MMDB_s` may cause
us to write off the end of the struct unless the caller is recompiled.
> Revert ABI breaking change

- src/maxminddb.c
If the library is not compiled with unicode. Then `CreateFile` points to `CreateFileA`. And will be called with a wide string.
> Don't force wide string on possibly `CreateFileA`.

- Changes.md
- bin/mmdblookup.c
- doc/libmaxminddb.md
- src/maxminddb.c
- t/get_value_pointer_bug_t.c
- t/maxminddb_test_helper.c
- t/metadata_t.c
> Fix heap buffer overflow

- dev-bin/make-man-pages.pl
Follow-up to #248. Sorry to do this peacemeal, but lowdown started supporting `-M` only with 0.8.1, released… today. (I wouldn't expect anyone generating manpages to not have a latest lowdown. I don't even know if there are others besides me ;)). On the plus side, the changelog entry for 1.5.1 is already there and doesn't need an update? :)
I hope to converge geoipupdate's and libmaxminddb's `dev-bin/make-man-pages.pl` eventually, but while one of the commits below is in that direction, I'm not there yet. If you have more copies of that in other MaxMind projects, happy to incorporate those as well and have one source for all.
Thanks for the consideration!
> A couple more manpage improvements

- CMakeLists.txt
The `target_include_directories` option doesn't work as expected. I noticed that when trying to include the libmaxminddb as a CMake subdirectory into a different project.
Here is a simple reproducer:
```
project(reproducer)
add_subdirectory("libmaxminddb")
```
CMake will fail on building that project with the following error:
```
CMake Error in libmaxminddb/CMakeLists.txt:
Target "maxminddb" INTERFACE_INCLUDE_DIRECTORIES property contains path:
"/tmp/repro/libmaxminddb/"
which is prefixed in the build directory.
```
The problem seems to be two-fold:
- The variable in `$<BUILD_INTERFACE:${VAR}>` must be a single path.
- The paths provided for build interface must not be relative.
The attached patch fixes the problem.
> build: cmake: fix target_include_directories

- CMakeLists.txt
`CMAKE_SHARED_LIBRARY_PREFIX` defaults to `lib` on UNIX systems but to an empty string on Windows which follows the conventions on these systems. The existing build forces the prefix on all platforms so the dynamic library produced by this setup on Windows will be `libmaxminddb.dll` (instead of `maxminddb.dll`).
This patch just removes the explicit configuration of the prefix so the dynamic library on Linux will be `libmaxminddb.so` and `maxminddb.dll` on Windows.
I'm not sure if this hard-coded prefix was intentional. I'm working on Conan package for libmaxmminddb and I have to include this patch to make linking work on Windows. It could be something specific to Conan though but I think the change makes sense.
> build: cmake: remove lib prefix on Windows

- CMakeLists.txt
The .dll files are not installed on Windows when libmaxminddb is built as a shared library.
A shared on Windows consist of the `.dll` with the actual code and `.lib` with the description of symbols. Weirdly enough, the `.dll`s are installed into runtime directory and `.lib`s into the libraries directory.
The install target in CMake installs only `ARCHIVE` and `PUBLIC_HEADER` objects. To support Windows, it either needs to include `RUNTIME` as well or the install command doesn't need to list the objects types. This PR uses the later approach.
> build: cmake: fix installation of .dll files on Windows

- CMakeLists.txt
When build libmaxminddb as a dynamic library on Windows, the `.lib` file is not created as the symbols in the library are not annotated with `__declspec(dllimport)`. This can be workaround with `WINDOWS_EXPORT_ALL_SYMBOLS` CMake property.
Easiest workaround is to configure with `cmake -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON`.
This patch enables the above property on the `maxminddb` target only which seems to be a cleaner solution.
> build: cmake: export all symbols on Windows

- bin/CMakeLists.txt
If host is iOS/tvOS/watchOS, executables are BUNDLE and need a destination since https://cmake.org/cmake/help/latest/policy/CMP0006.html, otherwise CMake configuration fails.
> CMake: fix cross-build to iOS/tvOS/watchOS

- src/maxminddb.c
> only use FD_CLOEXEC if O_CLOEXEC is not available

- CMakeLists.txt
CMakeLists.txt currently does not detect a `lib64` libdir for installation on linux systems using such directory structures.
This is a small patch to allow such directories to be detected and used.
> Allow for alternate libdir detection in linux

- bin/Makefile.am
- src/Makefile.am
* Add -no-undefined flag to build shared library, otherwise this error will show:
libtool: warning: undefined symbols not allowed in x86_64-w64-mingw32 shared libraries; building static only
* Add -municode flag for wmain in mmdblookup program.
> autotools: Add proper linker flags for mingw

- CMakeLists.txt
- Changes.md
- bin/CMakeLists.txt
- include/maxminddb.h
- t/CMakeLists.txt
- Only set PACKAGE_VERSION on WIN32 if not set
- Define PACKAGE_VERSION in .in file for CMake
> Set PACKAGE_VERSION in header file for CMake

- CMakeLists.txt
Propose to move generated file to binary directory because it creates from different CMake configuration at the same time and it is race condition
The problems occures when you have multiple CMake configurations for example Release, Relwithdebinfo, Debug.
And when you reload CMake at same time every configuration try to modify file in same location **maxminddb_config.h**.
So easiest fix is to move generated file per configuration.
> Fix file generation error on multiple CMake configurations reload

- include/maxminddb.h
- src/maxminddb.c
This typedef isn't needed in maxminddb.h since sa_family_t isn't part of this library's public API.  Moreover, it can conflict with typedefs in the headers of other libraries.  Move the typedef from maxminddb.h to maxminddb.c, where sa_family_t is used.
This change makes it possible to build [Zeek](https://github.com/zeek/zeek) with libmaxminddb on Windows using MSVC, something that currently fails because it depends on [libunistd](https://github.com/robinrowe/libunistd) and that also defines sa_family_t.
> Remove Windows sa_family_t typedef from public header

- Changes.md
- src/data-pool.c
- src/data-pool.h
- src/maxminddb.c
Also, add guards to follow-up calculations to error if they overflow.
Closes #335.
> Fix overflow in search_tree_size

- Changes.md
- src/maxminddb.c
> Define SSIZE_MAX conditionally on Windows

- CMakeLists.txt
- bin/CMakeLists.txt
* make binary build optional
* generate install targets optionally
> cmake: add options for binary build and install targets

- CMakeLists.txt
- bin/CMakeLists.txt
Actually use the defined variables in the pkg-config file, as well as for installing the `mmdblookup` binary.
> Make greater use of GNUInstallDirs

- CMakeLists.txt
- Changes.md
- configure.ac
- t/metadata_t.c
- t/read_node_t.c
- **Add change log entry for #346**
- **Update test submodule**
- **Set release date**
> Release 1.10.0

- CMakeLists.txt
- Changes.md
- NOTICE
- README.md
- doc/libmaxminddb.md
- doc/mmdblookup.md
- **Update copyright year**
- **Generate and install man pages with CMake**
> Install man pages with CMake

- CMakeLists.txt
Using the maxminddb vcpkg port causes a unnecessary include to a private build "generated" folder that is found when using pre-built vcpkg libraries in another project
> Fix Build issues from using vcpkg port

- .gitignore
- CMakeLists.txt
- README.fuzzing.md
- t/CMakeLists.txt
- t/fuzz_mmdb.c
- https://github.com/maxmind/libmaxminddb/commit/51347129b3fa4f09a7b8f58f22c6510648c41b93 Ignore build directory.
-  https://github.com/maxmind/libmaxminddb/commit/52128223b12abe26f5b097ae69acd559229202c5 Add `fuzz_mmdb` fuzz target.
These are the bugs i found https://github.com/maxmind/libmaxminddb/pull/356
My plans are to integrate [libmaxminddb](https://github.com/maxmind/libmaxminddb) into [OSS-Fuzz](https://google.github.io/oss-fuzz).
> Add fuzzing support in libmaxminddb

- src/maxminddb.c
- t/bad_pointers_t.c
While I was fuzzing, I found a total of three memory leaks. This is the patch.
> fix: memory leak in MMDB_open()

- Changes.md
- src/maxminddb.c
- t/bad_pointers_t.c
To avoid segfaults in callers that freed the parameter on error.
> Set entry parameter to NULL or valid memory

- CMakeLists.txt
- Changes.md
- configure.ac
- src/data-pool.c
- t/data-pool-t.c
- t/fuzz_mmdb.c
- **Set release date**
- **Run clang-format**
- **Bumped version to 1.12.2**
> Release 1.12.2

- .clang-format
- Changes.md
- bin/mmdblookup.c
- include/maxminddb.h
- src/maxminddb.c
- t/maxminddb_test_helper.c
- t/maxminddb_test_helper.h
- **Do not rely on volatile for double/float decoding**
- **Improve endian check if macro is not set**
> Fix warnings in float/double functions
